version: '3.5'

services:
    wait-for-it:
        image: hanabosocom/wait-for-it:master

    app:
        image: hanabosocom/go-base:dev
        user: ${DEV_UID}:${DEV_GID}
        env_file:
            - .env
        volumes:
            - ./:/app
            - ${GOPATH}/pkg:/go/pkg
        ports:
            - ${DEV_IP}:8080:8080
            - ${DEV_IP}:6666:6666
        command: /run.sh -p main.go -c api -l 6666
        security_opt:
            - 'seccomp:unconfined'

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        ports:
            - ${DEV_IP}:3306:3306
        volumes:
            - mariadb:/var/lib/mysql

volumes:
  mariadb: {}